package hu.bme.aut.netcar;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


import java.util.List;
import java.util.Optional;

@Controller	// This means that this class is a Controller
@CrossOrigin
@RequestMapping
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private CarRepository carRepository;


	@PostMapping(path="/addUser") // Map ONLY POST Requests
	public @ResponseBody
	DefaultResponse addNewUser (@RequestBody User user) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		List<User> users = userRepository.findAll();

		for (User u : users) {
			if (u.getEmail().equals(user.getEmail()))
				return new DefaultResponse("EMAIL_ALREADY_USED");
		}

		Car c = new Car();
		c.setUser(user);

		userRepository.save(user);
		carRepository.save(c);
		return new DefaultResponse("SUCCESSFUL_REGISTRATION");
	}

	@GetMapping(path="/getAllUsers")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path = "/getUser/{id}")
	public  @ResponseBody  Optional<User> getUserById(@PathVariable(value = "id") Integer UserId)
	{
		//	.orElseThrow(() -> new ResourceNotFoundException("Employee not found for this id :: " + employeeId));
		return userRepository.findById(UserId);
	}

	@GetMapping(path = "/getUserByName/{username}")
	public @ResponseBody User findUserByName(@PathVariable String username) {
		return userRepository.findByName(username);
	}

	@PutMapping(value = "/updateUser/{id}", produces = "application/json")
	public @ResponseBody
	DefaultResponse updateUser(@PathVariable(value = "id") Integer id,
							   @RequestBody User param){
		User user = userRepository.findById(id).get();
		user.setEmail(param.getEmail());
		user.setName(param.getName());
		user.setPassword(param.getPassword());
		user.setPictureUrl(param.getPictureUrl());
		user.setCredits(param.getCredits());
		userRepository.save(user);

		return new DefaultResponse("USER_SUCCESSFUL_UPDATED");
		//return new Collections.singleton("response");
	}

<<<<<<< HEAD
	@PutMapping(value = "/updateUserValidation/{id}", produces = "application/json")
	public @ResponseBody
	DefaultResponse updateUserValidation(@PathVariable(value = "id") Integer id){
		User user = userRepository.findById(id).get();
		user.setValid(true);
		userRepository.save(user);

		return new DefaultResponse("USER_SUCCESSFUL_UPDATED");
		//return new Collections.singleton("response");
	}

=======
>>>>>>> parent of 1fdd6bc... Validation
	@RequestMapping(value="/deleteUser/{id}", method={RequestMethod.DELETE, RequestMethod.GET})
	public @ResponseBody
	DefaultResponse deleteUser(@PathVariable(value = "id") Integer id){
		Optional<User> OptionalUser = userRepository.findById(id);
		User user = OptionalUser.get();
		userRepository.delete(user);
				return new DefaultResponse("deleted user with id: "+id);
	}

	@PostMapping(path="/login")
	public @ResponseBody
	LoginResponse Login (@RequestParam String email, @RequestParam String password) {
		List<User> list = userRepository.findAll();

		// Very simple authentication:
		for (User u : list) {
			if (u.getEmail().equals(email)) {
				if (u.getPassword().equals(password))
					return new LoginResponse("SUCCESSFUL_LOGIN", u.getId());
				else
					return new LoginResponse("WRONG_PASSWORD", null);
			}
		}

		return new LoginResponse("NO_EMAIL_FOUND", null);
	}


// ----------------------------------------------------------------------------- Car

	//GET ALL CARS
	@GetMapping(path="/getAllCars")
	public @ResponseBody Iterable<Car> getAllCars() {
		// This returns a JSON or XML with the users
		return carRepository.findAll();
	}

	// GET CAR
	@GetMapping(path = "/getCar/{id}")
	public  @ResponseBody  Optional<Car> getCarById(@PathVariable(value = "id") Integer Id)
	{
		//	.orElseThrow(() -> new ResourceNotFoundException("Employee not found for this id :: " + employeeId));
		return carRepository.findById(Id);
	}
	//UPDATE CAR
	@PutMapping(path = "/getUser/{id}/updateCar")
	public @ResponseBody
	DefaultResponse updateCar(@PathVariable(value = "id") Integer id, @RequestParam String brand,
							  @RequestParam String model, @RequestParam String serial,
							  @RequestParam String picUrl, @RequestParam boolean hasBoot
							  //@RequestParam int seat, @RequestParam int placeInBoot
	){
		Car car = carRepository.findById(id).get();
		car.setBrand(brand);
		car.setModel(model);
		car.setSerial(serial);
		car.setPicUrl(picUrl);
		car.setHasBoot(hasBoot);
		/*car.setSeat(seat);
		car.setPlaceInBoot(placeInBoot);
		car.setFreeSeat(seat);
		car.setFreePlace(seat + placeInBoot);*/
		carRepository.save(car);

		return new DefaultResponse("Updated car with id: " +  id);
	}

	//DELETE CAR
	@PutMapping(path = "/getUser/{id}/deleteCar")
	public @ResponseBody
	DefaultResponse deleteCar(@PathVariable(value = "id") Integer id){
		updateCar(id,null,null,null, null, false);

		return new DefaultResponse("deleted car with id: " +  id);
	}
}
